insert into USER_FOLLOW_TOPICS (FOLLOWERS_ID, FOLLOW_TOPICS_ID) values (1, 12);
insert into USER_FOLLOW_TOPICS (FOLLOWERS_ID, FOLLOW_TOPICS_ID) values (1, 2);
insert into USER_FOLLOW_TOPICS (FOLLOWERS_ID, FOLLOW_TOPICS_ID) values (20, 44);
